name: PetJournalAndroid

# Eventos/Events: vão disparar quando uma das ações acontecerem.
# EXEMPLO: evento abaixo dispara quando acontecer um push em uma das branches explicitadas
on:
  push:
    branches:
      - develop
      - cicdtest
      - 'instTest/nameAndGender'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'

      - name: Set up Android SDK
        uses: reactivecircus/android-setup@v2
        with:
          components: platform-tools,build-tools-30.0.3

      - name: Build and test
        run: ./gradlew test